name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.36

      - name: Fix SDKMANAGER path
        run: |
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/licenses
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $HOME/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $HOME/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo "24333f8a63b6825ea9c5514f83c1059f6ea6b044" >> $HOME/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          # Si buildozer a déjà téléchargé cmdline-tools, on le copie à l'ancien endroit où il le cherche
          if [ -d "$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin" ]; then
            cp $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager $HOME/.buildozer/android/platform/android-sdk/tools/bin/ || true
          fi
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bara-face-apk
          path: bin/*.apk
